sudo: required
branches:
  only:
    - master

services: docker
install: true

env:
  global:
  - OTP_URL=opentripplanner-hb:8080/otp/routers/hb/index/graphql
  - ORG=mfdz
  - DOCKER_USER=lehrenfried


language: C

script: ./travis-build.sh

