name: Run CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  global:
    # this is set to a Finnish API server as we need a working API for the map server to start. of course it doesn't return
    # useful information for Germany but at least we can test that the tiles exist (even though they are empty).
    OTP_URL: api.digitransit.fi/routing/v1/routers/hsl/index/graphql
    # the actual roadworks API server seems to block requests from the travis build hosts and therefore we need to override the URL and use static JSON hosted on Github
    ROADWORKS_API_URL: "https://gist.githubusercontent.com/leonardehrenfried/394c25941028670b5be26ef24248725d/raw/428c0c14cf6ee62f926a798fa7fda6755740185b/roadworks.json"
    ORG: mfdz
    DOCKER_USER: lehrenfried
    DOCKER_TAG: -latest
    DOCKER_IMAGE: $ORG/hsl-map-server:$DOCKER_TAG
    DOCKER_IMAGE_LATEST: $ORG/hsl-map-server:latest
    DOCKER_IMAGE_PROD: $ORG/hsl-map-server:prod

jobs:
  test:
    name: Run CI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential docker
      - name: Building docker image
        run: docker build --tag=$DOCKER_IMAGE -f Dockerfile .
      - name: Running docker image
        run: docker run --rm -p 8080:8080 -h hsl-map-server --name hsl-map-server -e OTP_URL=$OTP_URL -e ROADWORKS_API_URL=$ROADWORKS_API_URL $DOCKER_IMAGE &
      - name: Run test
        env:
          URL: http://localhost:8080/map/v1/roadworks-bw-map/16/34378/22618.pbf
          MINLENGTH: 20
        run: ./test.sh $URL $MINLENGTH
        shell: bash
      - name: Stopping docker image
        run: docker stop hsl-map-server
